# Generated by Django 6.0 on 2025-12-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_receipts_receipt_items_sticker_data_stickers'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipts',
            name='raw_ocr_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
