# Generated by Django 6.0 on 2025-12-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_receipts_raw_ocr_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker_data',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sticker_data',
            name='barcode_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sticker_data',
            name='barcodes_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
