# Generated by Django 6.0 on 2025-12-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sticker_data_barcode_sticker_data_barcode_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sticker_data',
            name='barcode_type',
        ),
        migrations.RemoveField(
            model_name='sticker_data',
            name='barcodes_json',
        ),
        migrations.AlterField(
            model_name='sticker_data',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
