# Generated by Django 6.0 on 2025-12-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_sticker_data_barcode_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt_items',
            name='status',
            field=models.CharField(default='processed', max_length=50),
        ),
    ]
