# Generated by Django 6.0 on 2025-12-11 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_receipt_items_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt_items',
            name='status',
        ),
    ]
