# Generated by Django 6.0 on 2025-12-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_receipt_items_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt_items',
            name='status',
            field=models.CharField(default='processed', max_length=50),
        ),
    ]
