# Generated by Django 6.0 on 2025-12-12 11:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_receipt_items_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker_data',
            name='matching_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='match_history',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('SKU', models.CharField(max_length=100)),
                ('receipt_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.receipt_items')),
                ('sticker_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.sticker_data')),
            ],
        ),
    ]
