# Generated by Django 6.0 on 2025-12-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sticker_data_matching_status_match_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker_data',
            name='matching_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('unmatched', 'Unmatched')], default='pending', max_length=20),
        ),
    ]
