# Generated by Django 6.0 on 2025-12-14 22:08

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_sticker_data_matching_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='image_path',
            field=models.FileField(upload_to=core.utils.receipt_upload_path),
        ),
    ]
