# Generated by Django 6.0 on 2025-12-15 11:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_receipts_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASINs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asin', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asins', to='core.user')),
            ],
            options={
                'unique_together': {('user', 'title', 'price', 'asin')},
            },
        ),
    ]
