# Generated by Django 6.0 on 2025-12-15 14:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_asins'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASIN_matches',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('asin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_items', to='core.asins')),
                ('receipt_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asin_matches', to='core.receipt_items')),
            ],
            options={
                'unique_together': {('receipt_item', 'asin')},
            },
        ),
    ]
