# Generated by Django 6.0 on 2025-12-15 14:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_asin_matches'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsinMatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('asin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.asins')),
                ('receipt_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asin_matches', to='core.receipt_items')),
            ],
        ),
        migrations.DeleteModel(
            name='ASIN_matches',
        ),
    ]
