# Generated by Django 6.0 on 2025-12-15 14:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_asinmatch_delete_asin_matches'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchedProducts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confidence', models.CharField(default='exact', max_length=20)),
                ('asin_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_matches', to='core.asins')),
                ('receipt_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asin_matches', to='core.receipt_items')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_products', to='core.user')),
            ],
            options={
                'unique_together': {('receipt_item', 'asin_record')},
            },
        ),
        migrations.DeleteModel(
            name='AsinMatch',
        ),
    ]
