# Generated by Django 6.0 on 2025-12-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_matchedproducts_delete_asinmatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt_items',
            name='status',
            field=models.CharField(choices=[('processed', 'Processed'), ('flagged for review', 'Flagged for Review'), ('unmatched', 'Unmatched'), ('matched', 'Matched')], default='processed', max_length=50),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='sticker_data',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('unmatched', 'Unmatched'), ('matched', 'Matched')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='stickers',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done')], default='pending', max_length=20),
        ),
    ]
