# Generated by Django 6.0 on 2025-12-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_receipt_items_matched_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt_items',
            name='matched_status',
        ),
        migrations.RemoveField(
            model_name='sticker_data',
            name='matched_status',
        ),
        migrations.AlterField(
            model_name='receipt_items',
            name='status',
            field=models.CharField(default='processed', max_length=50),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='sticker_data',
            name='matching_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('unmatched', 'Unmatched')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='sticker_data',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='stickers',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
