# Generated by Django 6.0 on 2025-12-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_receipt_items_matched_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt_items',
            name='matched_status',
            field=models.CharField(choices=[('matched', 'Matched'), ('unmatched', 'Unmatched')], default='unmatched', max_length=20),
        ),
        migrations.AddField(
            model_name='sticker_data',
            name='matched_status',
            field=models.CharField(choices=[('matched', 'Matched'), ('unmatched', 'Unmatched')], default='unmatched', max_length=20),
        ),
        migrations.AlterField(
            model_name='receipt_items',
            name='status',
            field=models.CharField(choices=[('processed', 'Processed'), ('flagged', 'Flagged for review')], default='processed', max_length=50),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='sticker_data',
            name='status',
            field=models.CharField(choices=[('processed', 'Processed'), ('flagged', 'Flagged for review')], default='processed', max_length=20),
        ),
        migrations.AlterField(
            model_name='stickers',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
