# Generated by Django 6.0 on 2025-12-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_receipt_items_matched_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker_data',
            name='matching_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done')], default='pending', max_length=20),
        ),
    ]
