# Generated by Django 6.0 on 2025-12-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_sticker_data_matching_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='asins',
            name='match_count',
            field=models.IntegerField(default=0),
        ),
    ]
