# Generated by Django 6.0 on 2025-12-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_asins_match_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchedproducts',
            name='match_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='matchedproducts',
            name='similarity_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='matchedproducts',
            name='confidence',
            field=models.CharField(choices=[('exact', 'Exact Match'), ('high', 'High Confidence'), ('medium', 'Medium Confidence'), ('partial', 'Partial Match'), ('low', 'Low Confidence')], default='medium', max_length=20),
        ),
    ]
