# Generated by Django 6.0 on 2025-12-17 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_matchedproducts_match_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchedproducts',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='matchedproducts',
            name='match_type',
        ),
        migrations.RemoveField(
            model_name='matchedproducts',
            name='similarity_score',
        ),
    ]
