# Generated by Django 6.0 on 2025-12-18 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_matchedproducts_confidence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt_items',
            name='matched_status',
        ),
    ]
